# Generated by Django 2.2.19 on 2022-12-01 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221130_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='api.Ingredient'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_amount', to='api.Recipes'),
        ),
    ]
