# Generated by Django 2.2.19 on 2022-12-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221204_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Лист покупок', 'verbose_name_plural': 'Листы покупок'},
        ),
    ]
